version: '3'
services: 
  web:
    image: webapp:auth-endpoint
    build:
      context: ./demo-app
      dockerfile: Dockerfile
    environment: 
      AUTH_SERVICE: "http://auth:8080/"
    depends_on: 
      - auth
    ports:
    - "3000:3000"
  auth:
    image: auth:auth-endpoint
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment: 
      PORT: "8080"
    expose:
      - "8080"